# QuTip Basics

- Import statements
  

In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt


## Quantum Object Class: Qobj
We represent matrices used in QM(quantum states and operators) as instances of the Quantum Object class, `Qobj`. It also contains properties that characterize the matrices, i.e. Data, Type, isHermitian, Dim, Shape. 

### Qobj delearation
Let's try generating a Pauli-Y matrix using two methods: 
- manually feeding `Qobj` with an array 
- using predifiend objects. 
  
Then, find its dimension and type.

In [2]:
y = np.array([[0, -1j], [1j, 0]])
pauli_y1 = Qobj(y)
print(pauli_y1)

pauli_y2 = sigmay()
print(pauli_y2)

print(pauli_y1.dims + [pauli_y1.type])


Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]
[[2], [2], 'oper']


### Qobj math
`Qobj` satisfy common matrix operation. But it's worth investigating matrix-scalar addition. Consider the following code, and it's clear that scalar-matrix addition is performed in a way that the scalar is added to each diagnal element.

In [3]:
a = np.array([[1,1,1],[1,1,1],[1,1,1]])
A = Qobj(a)
print(3 + A)


Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=True
Qobj data =
[[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


### Functions operate on Qobj
Consider several examples of methods that operate on Qobj class instances:

In [5]:
# norm of a Qobj
print(A.norm())

# trace of a Qobj
print(A.diag())

# full matrix representation of a Qobj
print(A.full())



3.0
[1. 1. 1.]
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


----
## Manipulating States and Operators
Below are several ways we can perform basic operations with states and operators.